export class BillDetail {
    private billNumber: string;
    private billType: string;
    private billVersion: string;
    private branch: string;
    private category: string;
    private collectionCode: string;
    private collectionName: string;
    private committees: [];
    private congress: string;
    private currentChamber: string;
    private dateIssued: Date;
    private detailsLink: string;
    private docClass: string;
    private governmentAuthor1: string;
    private governmentAuthor2: string;
    private isAppropriation: string;
    private isPrivate: string;
    private lastModified: Date;
    private members: [];
    private originChamber: string;
    private otherIdentifier: {};
    private packageId: string;
    private pages: string;
    private publisher: string;
    private related: {};
    private relatedLink: string;
    private session: string;
    private shortTitle: [];
    private suDocClassNumber: string;
    private title: string;
    
    constructor(data?: any){
            this.billNumber=data.billNumber;
            this.billType=data.billType;
            this.billVersion=data.billVersion;
            this.branch=data.branch;
            this.category=data.category;
            this.collectionCode=data.collectionCode;
            this.collectionName=data.collectionName;
            this.committees=data.committees;
            this.congress=data.congress;
            this.currentChamber=data.currentChamber;
            this.dateIssued=data.dateIssued;
            this.detailsLink=data.detailsLink;
            this.docClass=data.docClass;
            this.governmentAuthor1=data.governmentAuthor1;
            this.governmentAuthor2=data.governmentAuthor2;
            this.isAppropriation=data.isAppropriation;
            this.isPrivate=data.isPrivate;
            this.lastModified=data.lastModified;
            this.members=data.members;
            this.originChamber=data.originChamber;
            this.otherIdentifier=data.otherIdentifier;
            this.packageId=data.packageId;
            this.pages=data.pages;
            this.publisher=data.publisher;
            this.related=data.related;
            this.relatedLink=data.relatedLink;
            this.session=data.session;
            this.shortTitle=data.shortTitle;
            this.suDocClassNumber=data.suDocClassNumber;
            this.title=data.title;
    }
}
